### ISSUE TITLE
cloudscribe-core-ef and Authorize attribute

### ISSUE THREAD

**Issue by semsitivity** [joeaudette/cloudscribe.StarterKits#19]
Hi,
Starting from the cloudscribe-core-ef sample, I try to use the [Authorize] attribute on a controller.
Unfortunatelly, I receive an Exception:
System.InvalidOperationException: No authentication handler is configured to handle the scheme: Automatic
Is this relative to the multiTenant feature?

**Comment by joeaudette** [comment]
not enough information provided to reproduce the issue. Note that the ManageController in cloudscribe core has [Authorize] and it works fine when I login and click the username in the top nav which links to it.
Also I tried adding [Authorize] on the Contact method of the HomeController in the starter kit cloudscribe-core-ef and it works fine.

**Comment by joeaudette** [comment]
closing this, if you provide information to produce the problem I can re-open it
