### ISSUE TITLE
Migrations exception with MySQL provider

### ISSUE THREAD

**Issue by rshestakou** [joeaudette/cloudscribe.StarterKits#20]
Although you've [implemented the solution already](https://github.com/joeaudette/cloudscribe/blob/master/src/cloudscribe.Core.Storage.EFCore.Common/CoreEFStartup.cs#L29), I still get the exception when try to start any sample application that uses MySQL  with empty database:

`Unhandled Exception: System.AggregateException: One or more errors occurred. (Table 'compose.__EFMigrationsHistory' doesn't exist) ---> MySql.Data.MySqlClient.MySqlException: Table 'compose.__EFMigrationsHistory' doesn't exist`

So the simplest solution for me right now is to create this table manually first, and then everything is working well, but I believe it could be solved without any hacks.

**Comment by joeaudette** [comment]
this is a known issue, please read the [readme](https://github.com/joeaudette/cloudscribe.StarterKits/tree/master/cloudscribe-core-ef-mysql)

**Comment by rshestakou** [comment]
Right, but [here](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/68) and [here](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/99) you could see in answers that all should work fine, or maybe it's me who didn't get it properly.

**Comment by joeaudette** [comment]
should yes, but it doesn't

**Comment by Kagamine** [comment]
@rshestakou Could you ensure `lower_case_table_names=1`?

**Comment by yukozh** [comment]
This issue has been solved in 1.1.1-prerelease-10013.
