### ISSUE TITLE
Error with SQL on cloudscribe-idserver-ef

### ISSUE THREAD

**Issue by nigel-dewar** [joeaudette/cloudscribe.StarterKits#24]
Hi Joe,

There seems to be a bug with startker kit cloudscribe-idserver-ef. either that or I have not setup correctly.

I am getting the error: 
 
    An unhandled exception occurred while processing the request.

SqlException: The multi-part identifier "api.Id" could not be bound.
System.Data.SqlClient.SqlCommand+<>c.<ExecuteDbDataReaderAsync>b__107_0(Task<SqlDataReader> result)

I did setup an API in the project which works. And I copied the jsclient from the nodb sample over and modified to work with cloudscribe-idserver-ef. I carefully setup the client and the API in the admin area.

HAve you seen this error before?

**Comment by joeaudette** [comment]
that sounds like a bug, what steps to produce the error?

There have been new releases of IdentityServer4 so I need to update and see if any ocde changes are needed for that, but not sure how soon I will get to it

**Comment by nigel-dewar** [comment]
Hi Joe,

It just seems to be relative to the identity-ef starterkit for me at least. I loaded up the cloudscribe source, 'with all the source projects in it' and had no issues. 

I must have just set things up wrong. Ill close this. Cheers
