### ISSUE TITLE
appsettings.Development.json

### ISSUE THREAD

**Issue by achristov** [joeaudette/cloudscribe.StarterKits#32]
Any reason not to commit this?
EDIT: Missing in both solutions!

**Comment by joeaudette** [comment]
this repo is deprecated, nothing here has been updated for a long time.
To create cloudscribe apps please do not use the starterkits, instead use our project template for visual studio: https://marketplace.visualstudio.com/items?itemName=joeaudette.cloudscribeProjectTemplate

or our project template for dotnet new command
dotnet new -i "cloudscribe.templates::*"

in general our repos have appsettings.Development.json gitignored to prevent accidental commit of connection strings to the repo. So each developer who works with the solution needs to create that file.
